language: node_js
node_js:
- node
deploy:
  provider: npm
  email: coolspy107@gmail.com
  api_key:
    secure: pvahdL9X2tBBqfmcYuIwIY1+HI+39fu6F1yV4yJYasIrLIcLYrtaH09HBdqw2vD5XjMpKZXWEC5YThz0Rby/dQuXF8fVHznf9qpdKLnFktvSmHhDYZhNwA+4cOCgqi+KvMSMuYVOCNM8TGBbPNt9NqqrAqzen2SslWxiOujNpuy+tQ/lW7MPSVeJbyiw6yRbQYDVlpy5FoA8j8+1OSd0RMocLdRQvuRZmFqqes8/ppquvL8Io2AnVsUCWWIH2g+s3a8v7Hx9i5T9/DiIPo4hJ3GGkjOxUuRwE6/AaeKCfRAy/6MLD2b2jfDmStpYvuiJYJPYuwf0ODb4Q5M59pTkfjCARcGNgrzncBTZTkfNV+ADE5Vh6L96AnWBZ7deqSzt+0cLNvNQbRP0+IfIIBf8lRpbx7mbP0wBDeTC2fLmZ9CiXbNzy1+mXWQhK1nVWcQYvYc1Zdsk8GbWxPXt3WTstnBbdTGhXzpeqwPcFUR8avytHYNi/bs/xBUvh0nsLIQMpo/IyX1Hnd/4vJY5dWmrTZiHY8SZP8YyO0K9ZFmv0Fq4lL9p327lCg0gGG0I8wi3A3+cQ0fGSV2bsixJtmWdGk8t07xod4mWqK8ofBYgPS+D+NaJZKxMr3QDHeJqP+dvX9sDtTNEmbrkt6nzQeNwgTV2QZnbR0KkRYJrEzP9Vnk=
  on:
    tags: true
    repo: coolspy1007/cool-l-components
  skip_cleanup: 'true'
